backend:
  name: github
  repo: eugenedm/netlify-cms
  squash_merges: true

  # open_authoring: true
  # publish_mode: editorial_workflow

local_backend: true

site_url: https://cranky12345.netlify.app


media_folder: website/static/img
public_folder: /blog/img

docs_collection: &docs_collection
  folder: website/content/docs
  create: true
  summary: '{{weight}} - {{title}}'
  preview_path: 'docs/{{slug}}'
  sortable_fields: ['weight', 'title', 'group']
  fields:
    - label: Section
      name: group
      widget: relation
      collection: settings
      file: docs_sections
      search_fields: ['menu.docs.*.name', 'menu.docs.*.title']
      display_fields: ['menu.docs.*.title']
      value_field: 'menu.docs.*.name'
    - { label: 'Order', name: weight, widget: number }
    - { label: Title, name: title }
    - { label: Body, name: body, widget: markdown }

word_list: &word_list
  fields:
    - label: Extends
      name: extends
      widget: hidden
      default: 'existence'
    - label: Output message
      name: message
      widget: string
    - label: Ignore Case
      name: ignorecase
      widget: boolean
      default: true
      required: false
    - label: Notification Level
      name: level
      widget: select
      default: suggestion
      options:
        - { label: 'Suggestion', value: 'suggestion' }
        - { label: 'Warning', value: 'warning' }
        - { label: 'Error', value: 'error' }
    - label: Entries
      name: tokens
      widget: list

collections:
  - label: Settings
    name: settings
    hide: true
    files:
      - label: Docs Sections
        name: docs_sections
        file: website/site.yml
        fields:
          - label: menu
            name: menu
            widget: object
            fields:
              - label: Sections
                label_singular: Section
                name: docs
                widget: list
                summary: '{{title}} ({{name}})'
                fields:
                  - { label: 'Full Name', name: 'title', widget: 'string' }
                  - { label: 'Summary Name', name: 'name', widget: 'string' }




  - name: blog
    label: Blog
    label_singular: Post
    folder: website/content/blog
    show_preview_links: false

    preview_path: 'blog/{{year}}/{{month}}/{{title}}'
    create: true
    fields:
      - { label: Title, name: title }
      - { label: Author, name: author }
      - { label: Description (for blog list), name: description, widget: text }
      - {
          label: Meta Description (defaults to Description),
          name: meta_description,
          widget: text,
          required: false,
        }
      - { label: Twitter Image, name: twitter_image, widget: image }
      - { label: Date, name: date, widget: date }
      - { label: Body, name: body, widget: markdown }

