[build]
  base = "website/"
  command = "yarn install && yarn lint && yarn build"
  publish = "dist/"

  [build.environment]
    YARN_FLAGS = "--frozen-lockfile"
    YARN_VERSION = "1.22.4"

[[redirects]]
  from = "/auto/blog/*"
  to = "/:splat"

